name: CI/CD для мультимовного додатку

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Налаштування Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Встановлення залежностей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Перевірка структури файлів
      run: |
        ls -la
        ls -la translations/
        cat translations/messages.pot
    
    - name: Компіляція файлів перекладів
      run: |
        pybabel compile -d translations
