name: CI/CD для мультимовного додатку

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Налаштування Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Встановлення залежностей
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
    
    - name: Збірка Docker образу
      run: |
        docker build -t multilang-app .
    
    - name: Тестування мультимовності
      run: |
        docker run --rm multilang-app pytest tests/
    
    - name: Логін у Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Публікація Docker образу
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag multilang-app ${{ secrets.DOCKER_USERNAME }}/multilang-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/multilang-app:latest
