version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEFAULT_LANGUAGE=uk
    networks:
      - app_network
  
  # Симуляція апаратного забезпечення (умовно)
  hardware_simulator:
    build: ./hardware_simulator
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge
